# Generated by Django 4.2.3 on 2023-07-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.TextField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
