# Generated by Django 4.2.3 on 2023-07-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('book', models.ManyToManyField(related_name='purchases', to='book.book')),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
    ]
