# Generated by Django 4.2.3 on 2023-07-17 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ManyToManyField(related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
